### ISSUE TITLE
bug: Missing latest announcements from blackbasta

### ISSUE THREAD

**Issue by icecube54** [joshhighet/ransomwatch#68]
### host location

http://stniiomyjliimcgkvdszvgen3eaaoz55hreqqx6o77yvmpwt7gklffqd.onion/

### group name

blackbasta

### group information

![bastanews](https://github.com/joshhighet/ransomwatch/assets/135213864/9d256781-3f3f-41fa-87db-1c324d7000df)

The script is missing the latest victims (e.g. "Rheinmetall AG") from the blackbasta leak blog. 

### host

v3 (onion)

**Comment by 8linkz** [comment]
Hi

This is not an error but rather an inaccuracy.

Rheinmetal was hacked in Apiril and only now the data was published. Since BlackBasta does not specify the time, this can be a bit confusing.

proof of the hack from German media: https://www.tagesschau.de/inland/cyberangriff-rheinmetall-101.html

15.04.2023

Here is simply what happened: They published the data and thus Rheinmetal moved to the "front". 

greetings from Germany

**Comment by icecube54** [comment]
I'm sorry but https://github.com/joshhighet/ransomwatch/blob/main/posts.json is clearly missing a reference to "Rheinmetall" and others, so I guess it's a bug

**Comment by 8linkz** [comment]
hey,

thanks for your answer. I looked over it again and both the leak and the update after the data was published are missing - yes you are right it is an issue.

**Comment by joshhighet** [comment]
Thanks. Recent claims were being indexed with the wrong value after a change in HTML tags. I have updated the parser and updated previous entries to reflect accordingly.
