### ISSUE TITLE
Feature request: RSS Feed

### ISSUE THREAD

**Issue by abushenanigans** [joshhighet/ransomwatch#84]
We really appreciate the hard work the team has put into this. We are currently utilizing the JSON posts file, however, a RSS feed would be greatly beneficial, allowing for integration into Slack, Mattermost, etc.

**Comment by joshhighet** [comment]
thanks, not planning on adding unless this is is a PR proposal you intend on contributing at this time. you will likely find benefit in https://ransomware.live/rss.xml from @JMousqueton

**Comment by joshhighet** [comment]
Push notifications from this dataset can be painful to deal with due to the flat file structure of the JSON, limiting pagination and entry offsets. Here are examples that leverage this dataset if you are looking for build inspiration

https://github.com/vxunderground/ThreatIntelligenceDiscordBot
https://infosec.exchange/@ransomwatch
https://github.com/uforia/MatterBot
